# https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

patreon: alexelcu

# We need to apply here: https://github.com/sponsors
# github: [alexandru, avasil]
