// Temporarily commented out due to sbt-site dependency issue
// addSbtPlugin("com.47deg"          % "sbt-microsites"                % "1.4.4")
addSbtPlugin("com.github.sbt"     % "sbt-dynver"                    % "5.1.1")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"                       % "2.3.1")
addSbtPlugin("com.github.sbt"     % "sbt-unidoc"                    % "0.6.1")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"               % "1.1.4")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"                    % "5.10.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.20.2")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.5.10")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"                      % "2.8.2")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"                  % "0.5.2")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"                  % "3.12.2")
