name: build

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
    tags: ["v[0-9]+*"]

jobs:
  tests:
    name: Unit tests (scala ${{ matrix.scala }}, scala.js ${{ matrix.scalajs }}, jvm ${{ matrix.java }})
    strategy:
      fail-fast: true      
      matrix:
        os: [ubuntu-20.04]
        java: [8, 11]
        scala: [2.12.15, 2.13.8, 3.1.0]
        scalajs: [1.8.0]
        command: ["ci-test"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: sbt ++${{ matrix.scala }} ${{ matrix.command }}
        run: |
          ./.github/scripts/build.sh
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SCALAJS_VERSION: ${{ matrix.scalaJS }}
          SBT_COMMAND: ${{ matrix.command }}

  doc-tests:
    name: Docs tests 
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"

      - name: sbt ci-doc
        run: |
          sbt -J-Xmx6144m ci-doc
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SCALAJS_VERSION: ${{ matrix.scalaJS }}
          SBT_COMMAND: ${{ matrix.command }}

  #-----------------------------------------------------------------------------------
  # Publishing tasks
  #-----------------------------------------------------------------------------------

  publish_sonatype:
    name: Publish to Sonatype
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [ tests, doc-tests ]
    strategy:
      fail-fast: true      
      max-parallel: 1
      matrix:
        command: [ci-release]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"

      - name: Install GnuPG2
        run: |
          sudo apt-get update && sudo apt-get -y install gnupg2
          mkdir ~/.gnupg && chmod 700 ~/.gnupg
          echo use-agent >> ~/.gnupg/gpg.conf
          echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
          echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
          chmod 600 ~/.gnupg/*
          echo RELOADAGENT | gpg-connect-agent
          echo $PGP_SECRET | base64 --decode | gpg --import --no-tty --batch --yes
        env:
          PGP_SECRET: ${{secrets.PGP_SECRET}}

      - name: sbt ci-release
        run: |
          sbt -J-Xmx6144m +clean ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish_microsite:
    name: Publish Website
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [ publish_sonatype ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"

      - name: Set up Ruby 2.7 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Install microsite dependencies
        run: |
          bundle install --system --gemfile=site/Gemfile

      - name: Publish Website
        run: sbt +clean site/publishMicrosite
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
