name: manual-publish

on:
  workflow_dispatch:
    inputs:
      ref_to_publish:
        description: 'Ref (branch or tag)'
        required: true
        default: 'refs/heads/main'
      stable_version:
        description: 'Stable version? (true=staging, false=snapshot)'
        required: true
        default: "true"

jobs:
  publish_sonatype:
    name: Publish to Sonatype (Request)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
          ref: ${{ github.event.inputs.ref_to_publish }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          cache: 'sbt'
          java-version: 17
          distribution: 'temurin'

      - name: .github/scripts/release
        run: |
          .github/scripts/release
        env:
          PGP_KEY_HEX: ${{ secrets.PGP_KEY_HEX }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          PUBLISH_STABLE_VERSION: ${{ github.event.inputs.stable_version }}
          GITHUB_REF: ${{ github.event.inputs.ref_to_publish }}

  publish_docs:
    name: Publish Website
    needs: [ publish_sonatype ]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
          ref: ${{ github.event.inputs.ref_to_publish }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          cache: 'sbt'
          java-version: 17
          distribution: 'temurin'

      - name: Generate Scaladoc website
        run: ./sbt -J-Xmx6144m ci-doc

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/scala-3.3.7/unidoc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
